name: DeathChest
main: de.tobiyas.deathchest.DeathChest
version: 1.01
website: http://dev.bukkit.org/server-mods/deathchest/
author: Tobiyas
depend: [Vault]
softdepend: [WorldGuard, LWC]


description: >
             Fills a chest with your stuff, if you die.
commands:
# only for testing!
#  killself:
#    description: fsafsaf
#    aliases: []
#    usage: |
#           /<command>
  dcversion:
    description: displays the Version of DeathChest
    aliases: []
    usage: |
           /dcversion
  dcreload:
    description: reloads DeathChestConfig
    aliases: []
    usage: |
           /dcreload